name: Deploy to GH pages

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  BuildAndDeploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      # - name: Navigate to frontend directory
      #   run: cd apps/frontend

      - name: Install Dependencies
        run: yarn

      - name: Build Website
        run: yarn build

      - name: Deploy With CNAME
        # if: ${{ github.repository_owner == 'vechain' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/frontend/dist
          # cname: inspector.vecha.in
          force_orphan: true
